name: Create Release

on: workflow_call

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: Update dependencies
        run: |
          cd jagw
          sed -i 's/cacheServiceTag:.*$/cacheServiceTag: ${{ github.event.inputs.tag_name }}/' values.yaml
          sed -i 's/requestServiceTag:.*$/requestServiceTag: ${{ github.event.inputs.tag_name }}/' values.yaml
          sed -i 's/subscriptionServiceTag:.*$/subscriptionServiceTag: ${{ github.event.inputs.tag_name }}/' values.yaml
      - name: Create PR for local changes
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ github.token }}
          commit-message: Update dependencies
          committer: GitHub <noreply@github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: gh-action-temp
          base: dev
          title: 'Update dependencies'
          labels: automerge
      - name: Merge PR to dev
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
          PULL_REQUEST: "${{ steps.cpr.outputs.pull-request-number }}"
      - name: Check if branch was created
        # In previous steps, branch (and PR) only gets created if there were changes, otherwise not
        id: branch-exists
        run: |
          exists_locally=$(git rev-parse --verify --quiet gh-action-temp)
          if [[ -z ${exists_locally} ]]; then
              echo "::set-output name=exists::0"
          else
              echo "::set-output name=exists::1"
          fi
      - name: Delete temp branch if it exists
        if: steps.branch-exists.outputs.exists == 1
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ github.token }}
          branches: gh-action-temp
